# Generated by Django 3.0 on 2019-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMonumentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('township', models.TextField(blank=True, null=True)),
                ('range', models.TextField(blank=True, null=True)),
                ('part_of_section', models.CharField(blank=True, max_length=4, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=3)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Easement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easement_number', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FlatDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.PositiveIntegerField(blank=True, null=True)),
                ('map_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_sheets', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('cross_ref_area', models.PositiveIntegerField(blank=True, null=True)),
                ('cross_ref_section', models.PositiveIntegerField(blank=True, null=True)),
                ('cross_ref_map_number', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IndexCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monument_number', models.CharField(blank=True, max_length=255, null=True)),
                ('township', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('corner', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.PositiveIntegerField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cabinet_number', models.CharField(blank=True, max_length=255, null=True)),
                ('drawer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RightOfWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_tab', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SurplusParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surplus_parcel', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.PositiveIntegerField(blank=True, null=True)),
                ('map_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_sheets', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('cross_ref_area', models.PositiveIntegerField(blank=True, null=True)),
                ('cross_ref_section', models.PositiveIntegerField(blank=True, null=True)),
                ('cross_ref_map_number', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='')),
            ],
        ),
    ]
