# Generated by Django 3.0 on 2019-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0002_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source_file',
            field=models.FileField(upload_to='BOOKS'),
        ),
        migrations.AlterField(
            model_name='controlmonumentmap',
            name='source_file',
            field=models.FileField(upload_to='CONTROL_MONUMENT_MAPS'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='source_file',
            field=models.FileField(upload_to='DOSSIER_FILES'),
        ),
        migrations.AlterField(
            model_name='easement',
            name='source_file',
            field=models.FileField(upload_to='EASEMENTS'),
        ),
        migrations.AlterField(
            model_name='flatdrawing',
            name='source_file',
            field=models.FileField(upload_to='FLAT_DRAWINGS'),
        ),
        migrations.AlterField(
            model_name='indexcard',
            name='source_file',
            field=models.FileField(upload_to='INDEX_CARDS'),
        ),
        migrations.AlterField(
            model_name='license',
            name='source_file',
            field=models.FileField(upload_to='LICENSES'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='source_file',
            field=models.FileField(upload_to='PROJECT_FILES'),
        ),
        migrations.AlterField(
            model_name='rightofway',
            name='source_file',
            field=models.FileField(upload_to='RIGHT_OF_WAY'),
        ),
        migrations.AlterField(
            model_name='surplusparcel',
            name='source_file',
            field=models.FileField(upload_to='DEEP_PARCEL_SURPLUS'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='source_file',
            field=models.FileField(upload_to='SURVEYS'),
        ),
        migrations.AlterField(
            model_name='title',
            name='source_file',
            field=models.FileField(upload_to='TITLES'),
        ),
    ]
