# Generated by Django 2.2.8 on 2019-12-19 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0003_source_file_upload_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='area',
        ),
        migrations.AddField(
            model_name='survey',
            name='range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), size=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='township',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update')], max_length=6),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='section'
        ),
        migrations.AddField(
            model_name='survey',
            name='section',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), size=None),
        ),
    ]
