# Generated by Django 2.2.8 on 2019-12-20 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0004_array_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmonumentmap',
            name='range',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='controlmonumentmap',
            name='section',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='controlmonumentmap',
            name='township',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
