# Generated by Django 2.2.8 on 2019-12-20 21:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0008_book_range_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='township',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlmonumentmap',
            name='section',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='section',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='township',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
    ]
