# Generated by Django 2.2.8 on 2020-01-22 19:55

from django.db import migrations
import docsearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0009_range_and_array_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='range',
            field=docsearch.models.InclusiveIntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=docsearch.models.InclusiveIntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='township',
            field=docsearch.models.InclusiveIntegerRangeField(blank=True, help_text='Specify the lower and upper bounds for the range of values represented by this field. If this field only has one value, set it as both the lower and upper bounds.', max_length=255, null=True),
        ),
    ]
