# Generated by Django 2.2.8 on 2020-01-28 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0010_license_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=list, help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
        migrations.AddField(
            model_name='license',
            name='section',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=list, help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
        migrations.AddField(
            model_name='license',
            name='township',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=list, help_text='Set multiple values for this field by separating them with commas. E.g. to save the values 1, 2, and 3, record them as 1,2,3.', size=None),
        ),
    ]
