# Generated by Django 2.2.8 on 2020-01-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0011_license_plss_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='agreement_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
