# Generated by Django 2.2.10 on 2020-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0013_license_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatdrawing',
            name='building_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Building ID'),
        ),
    ]
