# Generated by Django 2.2.10 on 2020-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0013_license_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='controlmonumentmap',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deeptunnel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='easement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flatdrawing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indexcard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='license',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rightofway',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surplusparcel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='title',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=6),
        ),
    ]
