# Generated by Django 2.2.13 on 2025-05-20 14:47

import django.contrib.postgres.fields
from django.db import migrations, models
import docsearch.models
import docsearch.validators


class Migration(migrations.Migration):

    dependencies = [
        ('docsearch', '0015_auto_20230829_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='job_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='control number'),
        ),
    ]
