# Generated by Django 2.2.13 on 2026-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docsearch", "0016_auto_20250520_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deed", "Deed"),
                    ("land_acquisition", "Land Acquisition"),
                    ("receipts", "Receipts"),
                    ("condemnation", "Condemnation"),
                    ("legal_misc", "Legal Misc."),
                    ("appraisal", "Appraisal"),
                    ("plat_of_survey", "Plat of Survey"),
                    ("other", "Other"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
